services:
  pip-compile:
    entrypoint:
      - /bin/sh
      - -c
      - pip install pip-tools && pip-compile
    image: ghcr.io/informatica-na-presales-ops/qualys-api
    init: true
    volumes:
      - ./:/home/python/qualys-api
    working_dir: /home/python/qualys-api

  qualys-api:
    image: ghcr.io/informatica-na-presales-ops/qualys-api
    init: true

  shell:
    entrypoint:
      - /bin/sh
    image: ghcr.io/informatica-na-presales-ops/qualys-api
    init: true
    volumes:
      - ./:/home/python/qualys-api
    working_dir: /home/python/qualys-api
