services:
  qualys-api:
    image: ghcr.io/informatica-na-presales-ops/qualys-api
    init: true

  shell:
    image: ghcr.io/informatica-na-presales-ops/qualys-api
    init: true
    volumes:
      - ./:/home/python/qualys-api
    working_dir: /home/python/qualys-api
