###

GET {{api_url}}api/2.0/fo/asset/host/?action=list&host_metadata=all&truncation_limit=10&use_tags=1&tag_set_include={{tag_id}}
Authorization: Basic {{qualys_username}} {{qualys_password}}
X-Requested-With: Unknown

###

GET {{api_url}}api/2.0/fo/asset/host/vm/detection/?action=list&ids={{host_id}}&filter_superseded_qids=1&severities=4-5
Authorization: Basic {{qualys_username}} {{qualys_password}}
X-Requested-With: Unknown

###

GET {{api_url}}api/2.0/fo/knowledge_base/vuln/?action=list&last_modified_after=2021-12-11
Authorization: Basic {{qualys_username}} {{qualys_password}}
X-Requested-With: Unknown
